# GoReleaser v2 配置 —— 仅输出 Windows amd64 单文件
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: chatlog-windows-amd64
    binary: chatlog
    main: ./cmd/chatlog
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/sjzar/chatlog/pkg/version.Version={{.Version}}

archives:
  - id: default
    formats: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  draft: true
  prerelease: auto
  mode: replace
