name: Release Windows EXE (bare build, multi-arch)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows binaries
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: [amd64, 386, arm64]   # 64位、32位、ARM64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build (bare, no flags)
        shell: bash
        env:
          GOOS: windows
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1   # 允许 CGO，解决 go-lame / go-silk
        run: |
          go build -o chatlog-windows-${{ matrix.goarch }}.exe ./cmd/chatlog

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: chatlog-windows-${{ matrix.goarch }}.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
