name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Windows amd64
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.24
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: GoReleaser (windows/amd64 only)
        run: goreleaser release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
