name: Release Windows EXE only

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows amd64
    runs-on: windows-latest   # ← 关键：用 Windows 环境
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Windows executable
        shell: bash
        run: |
          go build -trimpath -ldflags="-s -w" -o chatlog-windows-amd64.exe ./cmd/chatlog

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: chatlog-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
