name: Release Windows amd64 EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows-amd64:
    name: Build Windows amd64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build (bare, no flags)
        shell: bash
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          go build -o chatlog-windows-amd64.exe ./cmd/chatlog

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: chatlog-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
